[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "fastapi-sam-adapter"
version = "0.1.0"
description = "An adapter to enable running APIs built with AWS SAM applications using FastAPI."
readme = {file = "README.md", content-type = "text/markdown"}
authors = [
    {name = "Noverde Developers", email = "dev@noverde.com.br"},
]
license = {text = "MIT"}
keywords = ["utilities", "fastapi", "sam"]
classifiers = [
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.8"
dependencies = [
    "uvicorn == 0.24.0",
    "fastapi == 0.104.1",
]
